learning_logs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path( 'll/', include( 'learning_logs_app.urls', 'll' ) ),
    path( 'mp/', include( 'mean_plans.urls', 'mp' ) ),
    path( 'users/', include( 'users.urls', 'users' ) ),
]

learning_logs_app/urls.py
"""URL patterns for learning_logs_app"""
from django.urls import path
from . import views

app_name = 'learning_logs_app'
urlpatterns = [
    path( '', views.index, name = 'index' ),
    path( 'index/', views.index, name = 'index' ),
    path( 'topics/', views.topics, name = 'topics' ),
    path( 'topic/<int:topic_id>/', views.topic, name = 'topic' ),
    path( 'new_topic/', views.new_topic, name = 'new_topic' ),
    path( 'new_entry/<int:topic_id>/', views.new_entry, name = 'new_entry' ),
    path( 'new_entry_any/', views.new_entry_any, name = 'new_entry_any' ),
    path( 'edit_entry/<int:entry_id>/', views.edit_entry, name = 'edit_entry' ),
]

users/urls.py
"""URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    #Defualt auth urls cover login, logout
    path( '', include( 'django.contrib.auth.urls' ) ),
    path( 'register/', views.register, name = 'register' ),
]

learning_logs_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic( models.Model ):
    """A topic the user is learning about"""
    LITERATURE = 'LI'
    SPORTS = 'SP'
    EDUCATION = 'ED'
    CHILDEDU = 'CED'
    ADULTEDU = 'AED'
    MISCELLANEOUS = 'MI'

    TOPIC_CATE_CHOICES = [
        ( LITERATURE, 'Literature' ),
        ( SPORTS, 'Sports' ),
        ( EDUCATION, (
                ( CHILDEDU, 'Children Education' ),
                ( ADULTEDU, 'Adult Education' ),
            ),
        ),
        ( MISCELLANEOUS, 'Miscellaneous'),
    ]

    topic_cate = models.CharField( 
        max_length = 3,
        choices = TOPIC_CATE_CHOICES,
        default = LITERATURE
    )

    owner = models.ForeignKey( User, on_delete = models.CASCADE )
    text = models.CharField( max_length = 200 )
    date_added = models.DateTimeField( auto_now_add = True )

    def __str__( self ):
        """Return a string representation of the model"""
        return f"{ self.text } - { self.get_topic_cate_display() }"


class Entry( models.Model ):
    """More details on the topic"""
    topic = models.ForeignKey( Topic, on_delete = models.CASCADE )
    text = models.TextField()
    date_added = models.DateTimeField( auto_now_add = True )


    class Meta:
        verbose_name_plural = 'entries'

    def __str__( self ):
        """A string representation"""
        rslt = self.text[ : 50 ] + '...' if len( self.text ) > 50 else self.text
        return rslt

learning_logs_app/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm( forms.ModelForm ):
    """For a form to setup a topic by user"""
    class Meta:
        model = Topic
        fields = [ 'topic_cate', 'text' ]
        labels = { 'topic_cate' : 'Topic category', 'text' : 'Text' }

class EntryForm( forms.ModelForm ):
    """For a form to insert an entry by user"""
    class Meta:
        model = Entry
        fields = [ 'text' ]
        labels = { 'text' : 'Entry:' }
        widgets = { 'text' : forms.Textarea( attrs = { 'cols' : 80 } ) }

class EntryAnyForm( forms.ModelForm ):
    """For a form to insert an entry of any topic by user"""
    class Meta:
        model = Entry
        fields = [ 'topic', 'text' ]
        labels = { 'topic' : 'Topic:', 'text' : 'Entry:' }
        widgets = { 'text' : forms.Textarea( attrs = { 'cols' : 80 } ) }

learning_logs_app/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm, EntryAnyForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.

#def index( request ):
#    """The homepage for learning_logs_app"""
#    return render( request, 'learning_logs_app/index.html' )

def not_owner( request, obj ):
    return obj.owner != request.user

def index( request ):
    return render ( request, 'learning_logs_app/index.html' )

@login_required
def topics( request ):
    """List all the topics so far"""
    #topics = Topic.objects.order_by( 'date_added' )
    #topics = Topic.objects.all().order_by( '-date_added' )
    topics = Topic.objects.all().filter( owner = request.user ).order_by( '-date_added' )
    context = { 'topics' : topics }
    return render( request, 'learning_logs_app/topics.html', context )

@login_required
def topic( request, topic_id ):
    """List of all entries under topic with the ID"""
    topic = Topic.objects.get( id = topic_id )
    if not_owner( request, topic ):
        raise Http404
    entries = topic.entry_set.order_by( '-date_added' )
    context = { 'topic' : topic, 'entries' : entries }
    return render( request, 'learning_logs_app/topic.html', context )

@login_required
def new_topic( request ):
    """Let user setup a topic"""
    if request.method != 'POST': #No data submitted - a blank form
        form = TopicForm()
    else: #data submitted - to process data
        form = TopicForm( data = request.POST )
        if form.is_valid():
            new_topic = form.save( commit = False )
            new_topic.owner = request.user
            new_topic.save()
            return redirect( 'learning_logs_app:topics' )

    context = { 'form' : form }
    return render( request, 'learning_logs_app/new_topic.html', context )

@login_required
def new_entry( request, topic_id ):
    """Let user add an entry of specific topic"""
    topic = Topic.objects.get( id = topic_id )
    if not_owner( request, topic ):
        raise Http404

    if request.method != 'POST': #No data to submit -> a blank form
        form = EntryForm()
    else: #Data found in POST mode
        form = EntryForm( data = request.POST )
        if form.is_valid():
            new_entry = form.save( commit = False )
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return redirect( 'learning_logs_app:topic', topic_id = topic_id )

    context = { 'form' : form, 'topic': topic }
    return render( request, 'learning_logs_app/new_entry.html', context )

@login_required
def new_entry_any( request ):
    """Let user an entry of any topic"""
    if request.method != 'POST': #No data yet to submit -> a blank form
        form = EntryAnyForm()
    else: #Date in POST mode
        form = EntryAnyForm( data = request.POST )
        if form.is_valid():
#            topic = form.get_topic()
            new_entry = form.save( commit = False)
            new_entry.owner = request.user
            new_entry.save()
            return redirect( 'learning_logs_app:topics' )#, topic_id = topic )

    context = { 'form' : form }
    return render( request, 'learning_logs_app/new_entry_any.html', context )

@login_required
def edit_entry( request, entry_id ):
    """Let user edit an entry"""
    entry = Entry.objects.get( id = entry_id )
    topic = entry.topic

    if not_owner( request, topic ):
        raise Http404

    if request.method != 'POST': #initial request filling the form
#        form = EntryForm( instance = entry )
        form = EntryAnyForm( instance = entry )
    else: #post submitted data for update
#        form = EntryForm( instance = entry, data = request.POST )
        form = EntryAnyForm( instance = entry, data = request.POST )
        if form.is_valid():
            form.save()
            return redirect( 'learning_logs_app:topic', topic_id = topic.id )

    context = { 'form' : form, 'topic' : topic, 'entry' : entry }
    return render( request, 'learning_logs_app/edit_entry.html', context )

learning_logs_app/templates/learning_logs_app/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang = 'en'>
  <head>
    <meta charset = 'utf-8'/>
    <meta name = 'viewport' content = 'width = device-width, initial-scale = 1, shrink-to-fit = no'/>
    <title>Learning Log app</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
  </head>
  <body>
    <nav class = 'navbar navbar-expand-md navbar-light bg-light mb-4 border'/>
      <a class = 'navbar-brand' href = "{% url 'learning_logs_app:index' %}">Learning Logs App</a>
      <button class = 'navbar-toggler' type = 'button' data-toggle = 'collapse' data-target = '#navbarCollapse' aria-controls = 'navbarCollapse' aria-expanded = 'false' aria-label = 'Toggle navigation'>
        <span class = 'navbar-toggler-icon'>
      </button>
      <div class = 'collapse navbar-collapse' id = 'navbarCollapse'>
        <ul class = 'navbar-nav mr-auto'>
          <li class = 'nav-item'>
            <a class = 'nav-link' href = "{% url 'learning_logs_app:topics' %}">Topics</a>
          </li>
        </ul>
        <ul class = 'navbar-nav ml-auto'>
          {% if user.is_authenticated %}
            <li class = 'nav-item'>
              <span class = 'navbar-text'>Hello, {{ user.username }}</span>
            </li>
	    <li class = 'nav-item'>
              <a class = 'nav-link' href = "{% url 'users:logout' %}">Log out</a>
            </li>
          {% else %}
            <li class = 'nav-item'>
              <a class = 'nav-link' href = "{% url 'users:register' %}">Register</a>
            </li>
            <li class = 'nav-item'>
              <a class = 'nav-link' href = "{% url 'users:login' %}">Log in</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main role = 'main' class = 'container'>
      <div class = 'pb-2 mb-2 border-bottom'>
        {% block page_header %} {% endblock page_header %}
      </div>
      <div>
        {% block content %} {% endblock content %}
      </div>
<p align = 'center' >-----Post template------</p>
    </main>
  </body>
</html>

learning_logs_app/templates/learning_logs_app/edit_entry.html
{% extends 'learning_logs_app/base.html' %}

{% block content %}

  <p>Edit entry:</p>
  <form action = "{% url 'learning_logs_app:edit_entry' entry.id %}" method = 'POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name = 'Submit'>Save change</button>
  </form>

{% endblock content %}

learning_logs_app/templates/learning_logs_app/index.html
{% extends 'learning_logs_app/base.html' %}
{% block page_header %}
  <div class = 'jumbotron'>
    <h1 class = 'display-3'>Track your learning...</h1>

    <p class = 'lead'>Learning logs help you keep track of your learnings, keeping a list of topics you're learning about with entries under each topics detailing what you have learned<p>

    <a class = 'btn btn-lg btn-primary' href="{% url 'users:register' %}" role = 'button'>Register &raquo;</a>
  </div>
{% endblock page_header %}

learning_logs_app/templates/learning_logs_app/new_entry.html
{% extends 'learning_logs_app/base.html' %}

{% block content %}

  <p>
    <a href = "{% url 'learning_logs_app:topic' topic.id %}">{{ topic }}</a>
  </p>
  
  <p>Add an entry</p>
  <form action = "{% url 'learning_logs_app:new_entry' topic.id %}" method = 'POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name = 'Submit'>Add entry</button>
  </form>

{% endblock content %}

learning_logs_app/templates/learning_logs_app/new_entry_any.html
{% extends 'learning_logs_app/base.html' %}

{% block content %}

  <p>Add an entry</p>
  <form action = "{% url 'learning_logs_app:new_entry_any' %}" method = 'POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name = 'Submit'>Add entry</button>
  </form>

{% endblock content %}

learning_logs_app/templates/learning_logs_app/new_topic.html
{% extends 'learning_logs_app/base.html' %}

{% block content %}

<p lign = 'center'>Add a topic</p>
<form action = "{% url 'learning_logs_app:new_topic' %}" method = 'post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name='submit'>Add topic</button>
</form>

{% endblock content %}

learning_logs_app/templates/learning_logs_app/topic.html
{% extends 'learning_logs_app/base.html' %}

{% block page_header %}
  <h3>Topic: {{ topic }}</h3>
{% endblock page_header %}

{% block content %}

  <p>Entries:</p>
  <p>
    <a href = "{% url 'learning_logs_app:new_entry' topic.id %}">Add an entry</a>
  </p>

  {% for entry in entries %}
    <div class = 'card mb-3'>
      <h5 class = 'card-header'>
        {{ entry.date_added|date:'M d, Y H:i' }}
	<small>
          <a href ="{% url 'learning_logs_app:edit_entry' entry.id %}">Edit entry</a>
	</small>
      </h5>
      <div class = 'card-body'>
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>No entry found for this topic yet.</p>
  {% endfor %}

{% endblock content %}

learning_logs_app/templates/learning_logs_app/topics.html
{% extends 'learning_logs_app/base.html' %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li>
        <h5>
          <a href = "{% url 'learning_logs_app:topic' topic.id %}">{{ topic }}</a>
	</h5>
      </li>
    {% empty %}
      <li>
        <h5>No topics have been created yet.</h5>
      </li>
    {% endfor %}
  </ul>

  <h5>
    <a href = "{% url 'learning_logs_app:new_topic' %}">Add a topic</a>
  </h5>
  <p>----<a href = "{% url 'learning_logs_app:new_entry_any' %}">Add en entry (of any topic)</a></p>
{% endblock content %}

<p>After the block</p>